[package]
name = "wtl"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
owo-colors = "4.0.0"
reqwest = { version = "0.11.23", features = ["blocking", "json"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
